name: Algolia Jekyll Action
description: Run jekyll-algolia plugin
author: Diego Hernangómez
branding:
  icon: 'search'
  color: 'purple'
inputs:
  APIKEY:
    description: 'Algolia API Key'
    required: true
  ruby-version:
    description: 'Version of Ruby to use on build. Default is 2.6.'
    required: false
    default: '2.6'
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache.'
    required: false
    default: 1
    
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        cache-version: ${{ inputs.cache-version }}
          
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ inputs.ruby-version }}-${{ inputs.cache-version }}
        restore-keys: |
            ${{ runner.os }}-gems-${{ inputs.ruby-version }}-${{ inputs.cache-version }}
    - name: Bundle install
      run: |
        # Bundle install
        echo "::group::Bundle install"
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        echo "::endgroup::"
      shell: bash
    - name: Exec jekyll algolia
      run: |
        # Updating Algolia Index
        echo "::group::Updating Algolia Index"
        bundle exec jekyll algolia
        echo "::endgroup::"
      env:
        ALGOLIA_API_KEY: '${{ inputs.APIKEY }}'
      shell: bash
